name: reforumasisten
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.2.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  file_picker: ^10.2.0
  tutorial_coach_mark: ^1.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/gambar/
    - assets/logo/

